In [1]:
# 최신 표준:Generator 객체 사용법(추천)

In [2]:
import numpy as np

# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [3]:
# rng.integers(low, high, size): 정수 무작위 추출

In [4]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[23 18 30 45 12  3]
[[2 7 3]
 [6 8 4]]


In [5]:
#rng.random(size): 0.0 이상 1.0 미만의 실수 추출

In [6]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.2001357  0.37775156]
 [0.11599972 0.9301834 ]
 [0.86611081 0.81517103]]


In [8]:
#rng.choice(a, size, replace): 샘플 추출 (복원/비복원)

In [9]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Banana' 'Orange']
['Grape' 'Apple' 'Orange']


In [10]:
#rng.shuffle(x)/rng.permutation(x): 무작위 무작위 셔플

In [11]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 반환값 없음(None)

원본: [1 2 3 4 5]
셔플본: [2 3 4 5 1]


확률 분포 기반 난수 생성 (통계·머신러닝 필수)

In [13]:
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[ 0.32811128 -0.61099936 -0.67451341 ...  0.49359468 -0.08386967
 -0.32856464]


In [14]:
# rng.uniform(low, high, size): 균등 분포 (Uniform)

In [15]:
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출
uniform_data = rng.uniform(10.0, 20.0, size=5)