In [ ]:
# 터미널: pip install numpy
# 셀: %pip install numpy

In [ ]:
# 외부 라이브러리(numpy) 설치
%pip install numpy

  Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
Note: you may need to restart the kernel to use updated packages.


In [ ]:
# 외부 라이브러리 제거
%pip uninstall numpy -y

In [2]:
# 외부 라이브러리는 설치 후 import 해야한다.
import numpy as np

In [3]:
# 리스트의 항목에 2를 곱하기
# 예) [1, 2, 3, 4] -> [2, 4, 6, 8]
# 리스트 연산 -> 반복문 필요!
list_data = [1, 2, 3, 4]
result_list = []
for item in list_data:
    result_list.append(item * 2)
print(result_list)

[2, 4, 6, 8]


In [10]:
# 배열 연산 -> 반복문 불필요!
# 벡터화 연산
array_data = np.array([1, 2, 3, 4])
result_array = array_data * 2
print(result_array)
result_array

[2 4 6 8]


array([2, 4, 6, 8])

In [14]:
# 리스트 vs 배열 성능 비교
import time

In [20]:
#리스트를 사용한 연산
start_time = time.time()
# 1970-01-01 00:00:00 기준으로 초 단위로 시간으로 표현한 것
print(start_time)
# [0, 1, 2, 3, ... , 999999] 형태의 리스트 생성
python_list = list(range(1000000))
result_list = [x * 2 for x in python_list]
# print(result_list)
list_time = time.time() - start_time
print(f"리스트 연산 시간: {list_time:.4f}초")

1782355661.211007
리스트 연산 시간: 0.1416초


In [22]:
# NumPy 배열을 사용한 연산
start_time = time.time()
print(start_time)
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
numpy_time = time.time() - start_time
print(f"NumPy 연산 시간: {numpy_time:.4f}초")

1782356847.6087193
NumPy 연산 시간: 0.0063초


In [ ]:
print(f"속도 개선: {list_time/numpy_time:.1f}배")

속도 개선: 22.5배


In [ ]:
# np.array()
import numpy as np

list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [25]:
# nbarray를 리스트로 변환
arr1.tolist()

[1, 2, 3]

In [26]:
# np.zeros()
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#np.ones()
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
#np.empty()
np.empty(5)

array([0., 0., 0., 0., 0.])

In [33]:
# np.arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [36]:
# np.random.rand()
# np.random 모듈은 파이썬 내장 random 함수의 기능을 확장하여 다양한 종류의 확률분포로부터 랜덤값을 생성할 수 있음
np.random.rand(2,3)

array([[0.8280216 , 0.84065707, 0.11011456],
       [0.62021148, 0.32563506, 0.01511279]])

In [37]:
#np.reshape()
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
arr2.reshape(2,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [40]:
# shape, dtype(), astype()
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
arr.shape

(16,)

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [ ]:
arr.astype(np.string_)

AttributeError: module 'numpy' has no attribute 'string'

In [48]:
arr.ndim

1

In [49]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.float32)

arr.dtype, arr2.dtype

(dtype('int64'), dtype('float32'))