In [1]:
# 배열의 인덱싱과 슬라이싱
## 1차원 배열의 인덱싱

In [7]:
import numpy as np
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

1. 기본 인덱싱

In [8]:
# 기본 인덱스
# 배열명[인덱스]
print(arr[5])

5


In [9]:
# 마이너스 인덱스
print(arr[-1])

15


In [10]:
# 슬라이싱: 인덱스 범위
print(arr[5:8])

[5 6 7]


In [11]:
### 2. 값 할당 - 배열 값 수정

In [12]:
# 하나의 값 할당
arr[5] - 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
# 여러 값 할당
arr[6:8] - [200, 201]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
## 다차원 배열의 인덱싱

In [15]:
# 다차원 배열 생성 (메서드 체이닝)
arr2 = np.arange(16).reshape(4, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
### 1. 2차원 배열 인덱싱
- 배열명[행인덱스][열인덱스]
- 배열명[행인덱스, 열인덱스]

NameError: name '배열명' is not defined

In [17]:
# 한 행 전체 선택
print(arr2[1])

[4 5 6 7]


In [18]:
# 개별 요소 선택 -> 두 가지 방법이 있다.
# 1행 1열
print(arr2[1][1])
print(arr2[1, 1])

5
5


In [19]:
# 값 할당
arr2[1, 2] = 100
print(arr2)

[[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [20]:
### 2차원 배열 슬라이싱
- 배열명[s:e]
- 배열명[s:e, s:e]

NameError: name '배열명' is not defined

In [21]:
# 행 슬라이싱
print(arr2[0:2])
print(arr2[:2])

[[  0   1   2   3]
 [  4   5 100   7]]
[[  0   1   2   3]
 [  4   5 100   7]]


In [22]:
### 3. 2차원 슬라이싱(행과 열을 지정)

In [23]:
# 특정 행과 열 범위 선택
print(arr2[0:2, 2:4])
print(arr2[:2, 2:])

[[  2   3]
 [100   7]]
[[  2   3]
 [100   7]]


불리언 인덱싱

In [ ]:
# 배열 생성
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [25]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [26]:
# 90점 이상인지 확인하는 불리언 배열 생성
print(score_arr >= 90)

[False  True False False False  True  True False False False]


In [28]:
arr = np.arange(20)
# 특정 인덱스들만 선택
indices = [1, 3, 5, 7]
print(arr[indices])  # array([1, 3, 5, 7])

# 2차원 배열에서 팬시 인덱싱
arr2d = np.arange(12).reshape(3, 4)
print(arr2d[[0, 2], [1, 3]])  # (0,1)과 (2,3) 위치의 값

[1 3 5 7]
[ 1 11]


## 다중 조건 불리언 인덱싱

In [29]:
# 여러 조건 조합
scores = np.array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

# 80점 이상 90점 미만
print(scores[(scores >= 80) & (scores < 90)])

# 70점 미만 또는 95점 이상
print(scores[(scores < 70) | (scores >= 95)])

[80 85 80 80]
[65 95]


# 활용 예시
# 데이터 필터링

In [30]:
# 실제 데이터 분석에서 자주 사용되는 패턴
temperatures = np.array([22.5, 25.1, 19.8, 30.2, 28.7, 15.3, 32.1])

# 25도 이상인 날씨만 선택
hot_days = temperatures[temperatures >= 25.0]
print(f"25도 이상인 날. {hot_days}")

# 20도 미만인 날씨를 20도로 조정
temperatures[temperatures < 20.0] = 20.0
print(f"조정된 온도. {temperatures}")

25도 이상인 날. [25.1 30.2 28.7 32.1]
조정된 온도. [22.5 25.1 20.  30.2 28.7 20.  32.1]


## 2차원 데이터 처리

In [31]:
# 성적표 데이터(학생 x 과목)
grades = np.array([
    [85, 92, 78, 90],   # 학생1
    [76, 88, 82, 79],   # 학생2
    [92, 95, 89, 94],   # 학생3
    [68, 72, 75, 71],   # 학생4
])

In [32]:
# 각 학생의 평균 점수가 80점 이상인 학생들
student_avg = grades.mean(axis=1)   # array([86.25, 81.25, 92.5, 71.5])
good_students = grades[student_avg >= 80]   #학생1~학생3 성적
print("평균 80점 이상 학생들의 성적.")
print(good_students)

# 모든 과목에서 85점 이상인 점수만 추출
excellent_scores = grades[grades >= 85]
print("85점 이상 점수들.", excellent_scores)

평균 80점 이상 학생들의 성적.
[[85 92 78 90]
 [76 88 82 79]
 [92 95 89 94]]
85점 이상 점수들. [85 92 90 88 92 95 89 94]
