In [1]:
# 배열의 인덱싱과 슬라이싱
## 1차원 배열의 인덱싱

In [2]:
import numpy as np
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

1. 기본 인덱싱

In [ ]:
# 기본 인덱스
# 배열명[인덱스]
print(arr[5])

5


In [5]:
# 마이너스 인덱스
print(arr[-1])

15


In [6]:
# 슬라이싱: 인덱스 범위
print(arr[5:8])

[5 6 7]


In [8]:
### 2. 값 할당 - 배열 값 수정

In [9]:
# 하나의 값 할당
arr[5] - 100
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [11]:
# 여러 값 할당
arr[6:8] - [200, 201]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:
## 다차원 배열의 인덱싱

In [13]:
# 다차원 배열 생성 (메서드 체이닝)
arr2 = np.arange(16).reshape(4, 4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
### 1. 2차원 배열 인덱싱
- 배열명[행인덱스][열인덱스]
- 배열명[행인덱스, 열인덱스]

NameError: name '배열명' is not defined

In [17]:
# 한 행 전체 선택
print(arr2[1])

[4 5 6 7]


In [18]:
# 개별 요소 선택 -> 두 가지 방법이 있다.
# 1행 1열
print(arr2[1][1])
print(arr2[1, 1])

5
5


In [22]:
# 값 할당
arr2[1, 2] = 100
print(arr2)

[[  0   1   2   3]
 [  4   5 100   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [ ]:
### 2차원 배열 슬라이싱
- 배열명[s:e]
- 배열명[s:e, s:e]

In [25]:
# 행 슬라이싱
print(arr2[0:2])
print(arr2[:2])

[[  0   1   2   3]
 [  4   5 100   7]]
[[  0   1   2   3]
 [  4   5 100   7]]


In [26]:
### 3. 2차원 슬라이싱(행과 열을 지정)

In [28]:
# 특정 행과 열 범위 선택
print(arr2[0:2, 2:4])
print(arr2[:2, 2:])

[[  2   3]
 [100   7]]
[[  2   3]
 [100   7]]
