In [12]:
# 배열의 연산과 변형
## 백터화 연산(Vectorized Operations)
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [13]:
## 백터화 연산(Vectorized Operations)
arr + 2

array([3, 4, 5, 6])

In [14]:
# 리스트
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [15]:
# 반복
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
arr = np.arange(1,5)
arr1 = np.arange(5, 9)
print(arr)
print(arr1)

[1 2 3 4]
[5 6 7 8]


In [17]:
arr + arr1

array([ 6,  8, 10, 12])

In [18]:
arr * arr1

array([ 5, 12, 21, 32])

In [19]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [20]:
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
list * list1

TypeError: can't multiply sequence by non-int of type 'list'

## 주요 산술 연산 함수
### 수학 함수들

In [22]:
# 제곱
print(np.square(arr))  # array([ 1,  4,  9, 16])

# 제곱근(루트)
print(np.sqrt(arr))    # array([1.        , 1.41421356, 1.73205081, 2.        ])

# exp(지수승)
print(np.exp(arr))     # array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# log
print(np.log(arr))     # array([0.        , 0.69314718, 1.09861229, 1.38629436])

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


## 배열 연산 함수들

In [23]:
# 더하기
print(np.add(arr, arr1))  # arr + arr1과 동일. array([ 6,  8, 10, 12])

# 합계
print(np.sum(arr))        # 10

# 누적합
print(np.cumsum(arr))     # array([ 1,  3,  6, 10])

[ 6  8 10 12]
10
[ 1  3  6 10]


## 통계 함수들

In [24]:
# 평균
print(np.mean(arr))     # 2.5

# 편차
print(np.var(arr))      # 1.25

# 표준편차
print(np.std(arr))      # 1.118033988749895

# 최솟값
print(np.min(arr))      # 1

# 최댓값
print(np.max(arr))      # 4

# 최솟값의 인덱스
print(np.argmin(arr))   # 0

# 최댓값의 인덱스
print(np.argmax(arr))   # 3

2.5
1.25
1.118033988749895
1
4
0
3


# 배열의 변형(Transformation)
## Transpose(축 변환)

In [25]:
# 2차원 배열의 축 변환
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
print(arr.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [27]:
print(arr.T) #arr.rtansposw()와 동일

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [30]:
# 3차원 배열의 축 변환
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [31]:
# 특정 축 순서 지정
print(arr3d.transpose(1, 0, 2))

[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


## 고급 연산 기법
### 브로드캐스팅
####shape이 다른 다차원배열 또는 스칼라 값 사이에서 연산이 가능